barcode_scanner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('scanner.urls')),
    path("", include('pwa.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

scanner/urls.py
from django.urls import path
from . import views
app_name = 'scanner'
urlpatterns = [
    path('test/', views.readBarcode, name = 'readBarcode'),
    path('scan/', views.scan_now, name = 'scan_now'),
    path('webcam/',views.webcam, name = 'webcam'),
    path('scanner/',views.webcam_form, name = 'scanner'),
    path('upload/', views.read_image, name = 'upload'),
    path('add_shelf/',views.AddShelf.as_view(), name = 'shelf'),
    path('',views.Shelves.as_view(), name = 'home'),
    path('<pk>/',views.ShelfDetailAdd.as_view(), name = 'shelf_details'),
    
    
    
]

scanner/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Shelf(models.Model):
    shelf = models.CharField(max_length = 255, unique = True)

    def __str__(self):
        return self.shelf
    def get_absolute_url(self):
        return reverse("scanner:shelf_details", kwargs = {'pk':self.id})

class Scan(models.Model):
    shelf = models.CharField(max_length = 255, null = True)
    code = models.CharField(max_length = 255, null = True)
    code_manually = models.CharField(max_length = 255, null = True, blank = True)
    qty = models.IntegerField()

    def __str__(self):
        return self.code

scanner/forms.py
from django import forms
from .models import Scan
class BarcodeForm(forms.ModelForm):
    class Meta:
        model = Scan
        fields = "__all__"
        widgets = {
            'shelf': forms.TextInput(attrs={'type': 'hidden'}),
        }

class ScanCode(forms.Form):
    # shelf = forms.CharField(label = "Shelf name or number")
    barcode = forms.ImageField(label = "Upload Image to scan",required=False)
    barcode_manually  =forms.CharField(label = "Scan Code or Manually add",required = False)
    qty = forms.IntegerField()

scanner/views.py
from django.shortcuts import render
import cv2
from pyzbar.pyzbar import decode
import time
from django.http import HttpResponse,StreamingHttpResponse,JsonResponse
import threading
from django.views.decorators import gzip
from .forms import BarcodeForm, ScanCode
from .models import Scan,Shelf
from django.views.generic import TemplateView,ListView,DetailView,CreateView,DeleteView,UpdateView,FormView
from django.urls import reverse_lazy
import numpy
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic.edit import FormMixin
from django.urls import reverse
import json
# Create your views here.

class AddShelf(CreateView):
    model = Shelf
    fields = ['shelf']
    template_name = 'scanner/add_shelf.html'
    success_url = reverse_lazy('scanner:shelf')

    def form_valid(self,model):
        request = self.request
        messages.add_message(request, messages.SUCCESS, 'SHELF ADDED SUCCESSFULLY!')
        return super().form_valid(model)

class Shelves(ListView):
    model = Shelf
    template_name  = 'scanner/home.html'


class ShelfDetailAdd(DetailView):
    model  = Shelf
    template_name = 'scanner/shelf_add_detail.html'
    success_url = reverse_lazy("scanner:shelf")

    def get_context_data(self, **kwargs):
        context = super(ShelfDetailAdd, self).get_context_data(**kwargs)
        context['form'] = ScanCode
        return context

    def post(self, request, *args, **kwargs):
        form = ScanCode(request.POST, request.FILES)
        if form.is_valid():
            request= self.request
            # Write Your Logic here
            shelf = request.POST.get('shelf')
            print("Shelf", shelf)
            image = form.cleaned_data.get('barcode')
            qty = form.cleaned_data.get('qty')
            manual_code = form.cleaned_data.get('barcode_manually')
            shelf_id = Shelf.objects.get(shelf=shelf).id
            # print(qty)
            if manual_code:
                obj = Scan.objects.filter(code=manual_code,shelf=shelf)
                if obj:
                    stock = Scan.objects.get(code=manual_code).qty
                    stock = stock + qty
                    obj = Scan.objects.filter(code=manual_code).update(qty=stock)
                    messages.add_message(request, messages.INFO, 'Stock updated successfully!')
                    return redirect(reverse("scanner:shelf_details", kwargs = {'pk':shelf_id}))
                elif not obj:
                    obj = Scan.objects.create(shelf=shelf,code=manual_code,qty=qty)
                    obj.save()
                    messages.add_message(request, messages.SUCCESS, 'STOCK ADDED SUCCESSFULLY!')
                    return redirect(reverse("scanner:shelf_details", kwargs = {'pk':shelf_id}))
            if image:
                img1 = cv2.imdecode(numpy.fromstring(image.read(), numpy.uint8), cv2.IMREAD_UNCHANGED)
                img = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
                # cv2.imshow(img)
                print("DECODED",len(decode(img)))
                if len(decode(img)) == 0:
                    messages.add_message(request, messages.ERROR, 'CODE HAD NO DATA, PLEASE TRY AGAIN!')
                    return redirect(reverse("scanner:shelf_details", kwargs = {'pk':shelf_id}))
                else:
                    for code in decode(img):
                        print(code.data.decode("utf-8"))
                        print(code.type)

                        if not code.data.decode("utf-8"):
                            print("No Data!")
                            messages.add_message(request, messages.ERROR, 'BARCODE COULD NOT BE READ, PLEASE TRY AGAIN!')
                        else:
                            obj = Scan.objects.filter(code=code.data.decode("utf-8"),shelf=shelf)
                            if obj:
                                stock = Scan.objects.get(code=code.data.decode("utf-8")).qty
                                stock = stock + qty
                                obj = Scan.objects.filter(code=code.data.decode("utf-8")).update(qty=stock)
                                messages.add_message(request, messages.INFO, 'Stock updated successfully!')
                                return redirect(reverse("scanner:shelf_details", kwargs = {'pk':shelf_id}))
                            elif not obj:
                                obj = Scan.objects.create(shelf=shelf,code=code.data.decode("utf-8"),qty=qty)
                                obj.save()
                                messages.add_message(request, messages.SUCCESS, 'STOCK ADDED SUCCESSFULLY!')
                                return redirect(reverse("scanner:shelf_details", kwargs = {'pk':shelf_id}))
            self.object = self.get_object()
            context = super(ShelfDetailAdd, self).get_context_data(**kwargs)
            context['form'] =  ScanCode
            return self.render_to_response(context=context)

        else:
            self.object = self.get_object()
            context = super(ShelfDetailAdd, self).get_context_data(**kwargs)
            context['form'] = form
            return self.render_to_response( context=context)





def readBarcode(request):

    cap = cv2.VideoCapture(0)
    cap.set(3,640)
    cap.set(4,480)
    camera = True

    used_codes = []



    while camera == True:
        success, frame = cap.read()

        for code in decode(frame):
            if code.data.decode('utf-8') not in used_codes:
                print("Approved")
                print(code.type)
                print(code.data.decode('utf-8'))
                used_codes.append(code.data.decode('utf-8'))
                time.sleep(5)
            elif code.data.decode('utf-8') in used_codes:
                print("CODE ALREADY SCANNED!")
                time.sleep(5)



        cv2.imshow("testing", frame)
        cv2.waitKey(1)
        # video = {
        #     "cap":cap,
        #     "img":img,
        #
        # }
        # return render(request,'scanner/test.html',video)

# class ReadImage(CreateView):
#     form_class = BarcodeForm
#     model = Scan
#     template_name = 'scanner/upload.html'
#     success_url = reverse_lazy('scanner:upload')
#     def form_valid(self,form):
#         request = self.request
#         image = form.cleaned_data.get('image')
#         qty = form.cleaned_data.get('qty')
#
#         print(image)
#         img = cv2.imdecode(numpy.fromstring(image.read(), numpy.uint8), cv2.IMREAD_UNCHANGED)
#
#         print(decode(img))
#
#         return super().form_valid(form)

def read_image(request):
    form = ScanCode()
    if request.method == "POST":
        form = ScanCode(request.POST,request.FILES)
        if form.is_valid():
            image = form.cleaned_data.get('barcode')
            qty = form.cleaned_data.get('qty')
            manual_code = form.cleaned_data.get('barcode_manually')
            # print(qty)
            if manual_code:
                obj = Scan.objects.filter(code=manual_code)
                if obj:
                    stock = Scan.objects.get(code=manual_code).qty
                    stock = stock + qty
                    obj = Scan.objects.filter(code=manual_code).update(qty=stock)
                    messages.add_message(request, messages.INFO, 'Stock updated successfully!')
                    return redirect("scanner:upload")
                elif not obj:
                    obj = Scan.objects.create(code=manual_code,qty=qty)
                    obj.save()
                    messages.add_message(request, messages.SUCCESS, 'STOCK ADDED SUCCESSFULLY!')
                    return redirect("scanner:upload")
            if image:
                img1 = cv2.imdecode(numpy.fromstring(image.read(), numpy.uint8), cv2.IMREAD_UNCHANGED)
                img = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
                print("DECODED",len(decode(img)))
                if len(decode(img)) == 0:
                    messages.add_message(request, messages.ERROR, 'CODE HAD NO DATA, PLEASE TRY AGAIN!')
                    return redirect("scanner:upload")
                else:
                    for code in decode(img):
                        print(code.data.decode("utf-8"))
                        print(code.type)

                        if not code.data.decode("utf-8"):
                            print("No Data!")
                            messages.add_message(request, messages.ERROR, 'BARCODE COULD NOT BE READ, PLEASE TRY AGAIN!')
                        else:
                            obj = Scan.objects.filter(code=code.data.decode("utf-8"))
                            if obj:
                                stock = Scan.objects.get(code=code.data.decode("utf-8")).qty
                                stock = stock + qty
                                obj = Scan.objects.filter(code=code.data.decode("utf-8")).update(qty=stock)
                                messages.add_message(request, messages.INFO, 'Stock updated successfully!')
                                return redirect("scanner:upload")
                            elif not obj:
                                obj = Scan.objects.create(code=code.data.decode("utf-8"),qty=qty)
                                obj.save()
                                messages.add_message(request, messages.SUCCESS, 'STOCK ADDED SUCCESSFULLY!')
                                return redirect("scanner:upload")
    return render(request, 'scanner/upload.html',{"form":form})


@gzip.gzip_page
def scan_now(request):
    try:
        cam = VideoCamera()
        return StreamingHttpResponse(gen(cam), content_type="multipart/x-mixed-replace;boundary=frame")
    except:
        return render(request, 'scanner/scan.html')


    return render(request,'scanner/scan.html',{})

class VideoCamera(object):
    def __init__(self):
        self.video = cv2.VideoCapture(0)
        (self.grabbed, self.frame) = self.video.read()

scanner/templates/scanner/add_shelf.html
{%extends 'base2.html' %}
{% block content %}
{% load django_bootstrap5 %}


<div class="container">
<h1>Add Shelf</h1>

<form class="" action="" method="post">{% csrf_token %}
  {% bootstrap_form form %}

  <button class = 'btn btn-primary' type="submit" name="button">Load</button>
</form>
</div>
{%endblock%}

scanner/templates/scanner/home.html
{% extends 'base2.html' %}
{% block content %}
{% load static %}

<div class="container  py-4">

<!-- <img src="{% static 'photo.jpg' %}" alt="not found"> -->
<h1>Shelves</h1>
<a id = "adds" class  = 'btn btn-warning'href="{% url 'scanner:shelf' %}">Add Shelves</a>
<hr>
<div class="row">


{% for shelf in shelf_list %}
    <!-- <a href="">{{shelf}}</a><br> -->
    <div class="col py-2">


    <div style = 'background-color:grey;' class="card">
  <div class="card-header">
    <b>{{shelf}}</b>
  </div>
  <div class="card-body">
    <a href="{{shelf.get_absolute_url}}" class="btn btn-primary">Load Barcodes</a>
  </div>
</div>
</div>
  {%empty%}
  <h3>Please add shelves to start scanning</h3>
  <!-- <a class = 'btn btn-primary' href="{% url 'scanner:shelf' %}">Add Shelves</a> -->

{%endfor%}
</div>


{%endblock%}
</div>

scanner/templates/scanner/shelf_add_detail.html
{% extends 'base2.html' %}{% load static %} {% block content %}
<style>

</style>

<body>
    <h1>Scan Codes for {{shelf}}</h1>
    <br/>
    <div class="container text-center">
        <div id="qr-reader"></div>
        <br>
        <div>
            <form onsubmit='spinner()' id='post-form' action="{% url 'scanner:scanner' %}" method="POST">{% csrf_token %}
                <input type="hidden" id='shelf' name='shelf' value="{{shelf}}">
                <label for="code">Auto Scan or Input Label</label>
                <input type="text" id="code" name='code' class="form-control" value="" required>
                <label for="qty">QTY</label>
                <input type="number" id='qty' name="qty" class="form-control">
                <br>
                <button id='btn' type="submit" class="btn btn-success">Add</button>
            </form>
        </div>
    </div>

    <script src="https://unpkg.com/html5-qrcode@2.0.9/dist/html5-qrcode.min.js"></script>
    <script>
        function onScanSuccess(decodedText, decodedResult) {
            var result = decodedText;
            console.log(result);
            document.getElementById('code').value = result;

        }

        var html5QrcodeScanner = new Html5QrcodeScanner(
            "qr-reader", {
                fps: 10,
                qrbox: 125,
            });
        html5QrcodeScanner.render(onScanSuccess);

        $('#post-form').on('submit', function(event) {
            event.preventDefault();
            console.log("form submitted!") // sanity check
            create_post()
        });
        // AJAX for posting
        function create_post() {
            console.log("create post is working!") // sanity check
            $.ajax({
                url: "/scanner/", // the endpoint
                type: "POST", // http method
                data: {
                    code: $('#code').val(),
                    qty: $('#qty').val(),
                    shelf: $('#shelf').val(),

                    csrfmiddlewaretoken: '{{ csrf_token }}',
                }, // data sent with the post request

                // handle a successful response
                success: function() {
                    //console.log(code);
                    //console.log(qty);
                    console.log("success");
                    alert("Successfully added!"); // another sanity check
                },
                error: function(e) {
                    //console.log(code);
                    //console.log(qty);
                    console.log("error");
                    console.log(e); // another sanity check
                    alert("An Error occured, please make sure all details are correct");
                    // another sanity check
                },


            });
        };

        function spinner() {
            document.getElementById("").innerHTML = "<i class='fa fa-spin fa-spinner'></i> Loading...";
        }
    </script>
</body>

{%endblock%}

scanner/templates/scanner/test.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <h1>Testing</h1>
  <body>

  </body>
</html>

scanner/templates/scanner/upload.html
{% extends 'base2.html' %}{% load static %} {% block content %}

<body>
    <h1>Scan Codes</h1>
    <br/>
    <div class="container text-center">
        <div id="qr-reader" style="width: 100%"></div>
        <br>
        <div>
            <form onsubmit='spinner()' id='post-form' action="{% url 'scanner:scanner' %}" method="POST">{% csrf_token %}
                <label for="code">Auto Scan or Input Label</label>
                <input type="text" id="code" name='code' class="form-control" value="" required>
                <label for="qty">QTY</label>
                <input type="number" id='qty' name="qty" class="form-control">
                <br>
                <button id='btn' type="submit" class="btn btn-success">Add</button>
            </form>
        </div>
    </div>

    <script src="https://unpkg.com/html5-qrcode@2.0.9/dist/html5-qrcode.min.js"></script>
    <script>
        function onScanSuccess(decodedText, decodedResult) {
            var result = decodedText;
            console.log(result);
            document.getElementById('code').value = result;

        }

        var html5QrcodeScanner = new Html5QrcodeScanner(
            "qr-reader", {
                fps: 10,
                qrbox: 250
            });
        html5QrcodeScanner.render(onScanSuccess);

        $('#post-form').on('submit', function(event) {
            event.preventDefault();
            console.log("form submitted!") // sanity check
            create_post()
        });
        // AJAX for posting
        function create_post() {
            console.log("create post is working!") // sanity check
            $.ajax({
                url: "/scanner/", // the endpoint
                type: "POST", // http method
                data: {
                    code: $('#code').val(),
                    qty: $('#qty').val(),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                }, // data sent with the post request

                // handle a successful response
                success: function() {
                    //console.log(code);
                    //console.log(qty);
                    console.log("success");
                    alert("Successfully added!"); // another sanity check
                },
                error: function(e) {
                    //console.log(code);
                    //console.log(qty);
                    console.log("error");
                    console.log(e); // another sanity check
                    alert("An Error occured, please make sure all details are correct");
                    // another sanity check
                },


            });
        };

        function spinner() {
            document.getElementById("").innerHTML = "<i class='fa fa-spin fa-spinner'></i> Loading...";
        }
    </script>
</body>

{%endblock%}

scanner/templates/scanner/webcam.html
{% extends 'base2.html' %}{% load static %} {% block content %}

<body>
    <h1>Scan Codes</h1>
    <br/>
    <div class="container text-center">
        <div id="qr-reader" style="width: 100%"></div>
        <br>
        <div>
            <form onsubmit='spinner()' id='post-form' action="{% url 'scanner:scanner' %}" method="POST">{% csrf_token %}
                <label for="code">Auto Scan or Input Label</label>
                <input type="text" id="code" name='code' class="form-control" value="" required>
                <label for="qty">QTY</label>
                <input type="number" id='qty' name="qty" class="form-control">
                <br>
                <button id='btn' type="submit" class="btn btn-success">Add</button>
            </form>
        </div>
    </div>

    <script src="https://unpkg.com/html5-qrcode@2.0.9/dist/html5-qrcode.min.js"></script>
    <script>
        function onScanSuccess(decodedText, decodedResult) {
            var result = decodedText;
            console.log(result);
            document.getElementById('code').value = result;

        }

        var html5QrcodeScanner = new Html5QrcodeScanner(
            "qr-reader", {
                fps: 10,
                qrbox: 250
            });
        html5QrcodeScanner.render(onScanSuccess);

        $('#post-form').on('submit', function(event) {
            event.preventDefault();
            console.log("form submitted!") // sanity check
            create_post()
        });
        // AJAX for posting
        function create_post() {
            console.log("create post is working!") // sanity check
            $.ajax({
                url: "/scanner/", // the endpoint
                type: "POST", // http method
                data: {
                    code: $('#code').val(),
                    qty: $('#qty').val(),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                }, // data sent with the post request

                // handle a successful response
                success: function() {
                    //console.log(code);
                    //console.log(qty);
                    console.log("success");
                    alert("Successfully added!"); // another sanity check
                },
                error: function(e) {
                    //console.log(code);
                    //console.log(qty);
                    console.log("error");
                    console.log(e); // another sanity check
                    alert("An Error occured, please make sure all details are correct");
                    // another sanity check
                },


            });
        };

        function spinner() {
            document.getElementById("").innerHTML = "<i class='fa fa-spin fa-spinner'></i> Loading...";
        }
    </script>
</body>

{%endblock%}