barcode_scanner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('scanner.urls')),
    path("", include('pwa.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

scanner/urls.py
from django.urls import path
from . import views
app_name = 'scanner'
urlpatterns = [
    path('test/', views.readBarcode, name = 'readBarcode'),
    path('scan/', views.scan_now, name = 'scan_now'),
    path('webcam/',views.webcam, name = 'webcam'),
    path('scanner/',views.webcam_form, name = 'scanner'),
    path('upload/', views.read_image, name = 'upload'),
    path('add_shelf/',views.AddShelf.as_view(), name = 'shelf'),
    path('',views.Shelves.as_view(), name = 'home'),
    path('<pk>/',views.ShelfDetailAdd.as_view(), name = 'shelf_details'),
    
    
    
]

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
    <title>Barcode Scanner</title>
    <script src="https://code.jquery.com/jquery-3.6.0.slim.js" integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/html5-qrcode@2.0.9/dist/html5-qrcode.min.js"></script>
  </head>
  <style media="screen">
    h1,h2,h3{
      text-align: center;
    }
    #adds{
      text-align: center;
    }
  </style>
  <body>

    <div class="container py-4">
      <h1>Barcode Scanner</h1>
      <div class="row">
      <div class="col-4">
        <a class = 'btn btn-success' href="/admin">Admin</a>
      </div>
      <div class="col-4">
        <a class = 'btn btn-success' href="{% url  'scanner:upload' %}">Add Without shelves</a>
      </div>
      <div class="col-4">
        <a class = 'btn btn-success' href="{% url  'scanner:home' %}">Home</a>
      </div>
      </div>
    </div>
    <div class="container py-4">
      {% for message in messages %}
      <div class="container-fluid pt-4 message">
        <div id = 'alert-custom' class="alert {{ message.tags }} alert-dismissible text-center" role="alert" >
          <h2>{{ message }}</h2>
        </div>
      </div>
      {% endfor %}

      {% block content %}


      {%endblock%}